// plugins/my-calculator/src/App.tsx
import { useEffect, useState } from 'react'
import Calculator from './Calculator'

export default function App() {
  const [enterAction, setEnterAction] = useState<{ code: string; type: string; payload: unknown; option: unknown }>({ code: '', type: '', payload: undefined, option: undefined })
  const [route, setRoute] = useState('')

  useEffect(() => {
    // ZTools 环境检查
    if (!window.ztools) {
      console.log('ZTools not detected, running in standalone mode')
      return
    }

    window.ztools.onPluginEnter((action) => {
      setRoute(action.code)
      setEnterAction(action)
    })
    window.ztools.onPluginOut(() => {
      setRoute('')
    })
  }, [])

  if (route === 'calculator') return <Calculator enterAction={enterAction} />

  return null
}

// plugins/killprocess/src/App.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import KillProcess from './KillProcess/index.vue'

const route = ref('killprocess')
const enterAction = ref<any>({})

onMounted(() => {
  window.ztools.onPluginEnter((action) => {
    route.value = action.code
    enterAction.value = action
  })
  window.ztools.onPluginOut(() => {
    route.value = ''
  })
})
</script>

<template>
  <KillProcess v-if="route === 'killprocess'" :enter-action="enterAction" />
</template>
